// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uoarsiguejouhgnhuuwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvYXJzaWd1ZWpvdWhnbmh1dXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NDI2MzksImV4cCI6MjA2ODAxODYzOX0.I69BuIzhaEfofwZ8rGSBvuZ5f9JomyO9bHVrFikNX8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});